version: '3.8'
services:
  app:
    image: golang:1.16
    volumes:
      - .:/app # Mount the current directory to /app inside the container
    working_dir: /app
    command: ["sh", "-c", "go build -o main && ./main"]
